### ISSUE TITLE
parameters usage not clear

### ISSUE THREAD

**Issue by davehouser1** [an0nlk/Nosql-MongoDB-injection-username-password-enumeration#1]
I cannot figure out how to use this program. 
The examples in the readme are too general I have nothing to relate to how to configure the parameters. 
Would find it helpful if you shared how you populate -up, -pp, -op, and -ep from an actual website.

**Comment by an0nlk** [comment]
> I cannot figure out how to use this program.
> The examples in the readme are too general I have nothing to relate to how to configure the parameters.
> Would find it helpful if you shared how you populate -up, -pp, -op, and -ep from an actual website.

Hi davehouser1,
For example, in the GitHub sign in page.

![image_2021-04-22_130839](https://user-images.githubusercontent.com/34982796/115675031-dc6ea900-a36b-11eb-8ece-614fce95821b.png)


You see that there are two text boxes for username and password. These are <input> tags. In the username input tag, the name is set to "login" which you must enter as -up.  And in the password the name is set to "password". which is the -pp. There are other parameters such as trusted_device, authenticity_token. these are the -op.
![zsdcsds](https://user-images.githubusercontent.com/34982796/115673136-e98a9880-a369-11eb-99ba-21ff703e99da.png)

If you need to get usernames from the database you should give the username's parameter name (login) as the -ep . 
So, the command is like this:
`python nosqli-user-pass-enum.py -u https://github.com/session -up login -pp password -ep login -op lauthenticity_token:XXXXXX,trusted_device:xxxxxx`
Hope you can understand now.
Thank you.
